project:
  type: website
  output-dir: docs
  
website:
  title: "Ana Clara Kaneko Ebert"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/ana-clara-kaneko-ebert-8811a815b/
      - icon: github
        href: https://www.github.com/AnaClaraEbert/mywebsite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Ana Clara Ebert"

format:
  html:
    theme: journal
    toc: true

editor: source

